name: LoginCheck
main: com.afeng.logincheck.LoginCheck
version: ${project.version}
api-version: ${api.version}
authors: [Liek_Girls]
description: ${plugin.description}
commands:
  logincheck:
    description: 主命令，身份查询、重载、玩家信息等
    usage: /logincheck <check|reload>
    aliases: [lc]
permissions:
  logincheck.check:
    description: 查询所有玩家和详细信息
    default: true
  logincheck.reload:
    description: 重载插件配置
    default: op
