name: LoginCheck
main: com.afeng.logincheck.LoginCheck
version: 1.1.1
api-version: 1.21
authors: [Liek_Girls]
description: 自动识别正版/离线身份并执行权限分配和广播。
commands:
  logincheck:
    description: 主命令，身份查询、重载、玩家信息等
    usage: /logincheck <check|reload>
    aliases: [lc]
permissions:
  logincheck.check:
    description: 查询所有玩家和详细信息
    default: true
  logincheck.reload:
    description: 重载插件配置
    default: op
