name: Release

on:
  push:
    tags:
      - "v*" # 仅在以 v 开头的标签推送时触发（如 v1.1.2）

permissions:
  contents: write # 允许写入 Release 内容

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新版 Ubuntu 作为构建环境

    steps:
      - name: 检出代码
        uses: actions/checkout@v4 # 拉取仓库代码

      - name: 设置 Java 环境
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # 选择 Temurin JDK
          java-version: "21"      # 使用 Java 21

      - name: 构建插件
        run: mvn clean package    # 使用 Maven 构建项目
        
      - name: 读取更新日志
        id: changelog
        run: |
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          awk '/^## /{if (p) exit; p=1; next} p' CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 上传 Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
          body: ${{ env.RELEASE_BODY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
